import { 
  FaBed, FaBath, FaRulerCombined, FaCoffee, FaCut, FaBlender, FaUtensils, FaPepperHot, FaMugHot, FaSnowflake, FaWineGlass, FaPlug, FaLock, FaFan, FaWindowMaximize, FaSpa, FaGamepad, FaCar, FaSwimmer, FaUmbrellaBeach, FaTv, FaWifi, FaTshirt, FaRegSmile, FaRegGrinStars, FaRegGrinBeam, FaRegGrinHearts, FaRegGrin, FaRegGrinTongue, FaRegGrinWink, FaRegLaugh, FaRegLaughBeam, FaRegLaughSquint, FaRegLaughWink, FaRegMeh, FaRegMehBlank, FaRegMehRollingEyes, FaRegSadCry, FaRegSadTear, FaRegSmileBeam, FaRegSmileWink, FaRegSurprise, FaRegTired, FaShower, FaSoap, FaToiletPaper, FaRegSun, FaRegMoon, FaRegStar, FaRegSnowflake, FaRegLightbulb, FaRegBell, FaRegClock, FaRegCalendarAlt, FaRegCalendarCheck, FaRegCalendarMinus, FaRegCalendarPlus, FaRegCalendarTimes, FaRegCheckCircle, FaRegCircle, FaRegDotCircle, FaRegTimesCircle, FaRegQuestionCircle, FaRegEdit, FaRegEye, FaRegEyeSlash, FaRegFlag, FaRegHeart, FaRegThumbsDown, FaRegThumbsUp, FaRegUser, FaRegUserCircle, FaRegUserSlash, FaRegAddressBook, FaRegAddressCard, FaRegBookmark, FaRegBuilding, FaRegCreditCard, FaRegEnvelope, FaRegFile, FaRegFileAlt, FaRegFolder, FaRegFolderOpen, FaRegImage, FaRegImages, FaRegListAlt, FaRegMap, FaRegNewspaper, FaRegPaperPlane, FaRegSave, FaRegStickyNote, FaRegWindowClose, FaRegWindowMaximize, FaRegWindowMinimize, FaRegWindowRestore, FaRegComment, FaRegCommentAlt, FaRegComments, FaRegEdit as FaRegEdit2, FaRegShareSquare, FaRegThumbsUp as FaRegThumbsUp2, FaRegThumbsDown as FaRegThumbsDown2, FaRegTrashAlt, FaRegBellSlash, FaRegCalendar, FaRegClock as FaRegClock2, FaRegClone, FaRegClosedCaptioning, FaRegCreditCard as FaRegCreditCard2, FaRegDotCircle as FaRegDotCircle2, FaRegEnvelopeOpen, FaRegFileArchive, FaRegFileAudio, FaRegFileCode, FaRegFileExcel, FaRegFileImage, FaRegFilePdf, FaRegFilePowerpoint, FaRegFileVideo, FaRegFileWord, FaRegFlag as FaRegFlag2, FaRegFlushed, FaRegFrown, FaRegFrownOpen, FaRegGrimace, FaRegGrinAlt, FaRegGrinBeamSweat, FaRegGrinHearts as FaRegGrinHearts2, FaRegGrinSquint, FaRegGrinSquintTears, FaRegGrinStars as FaRegGrinStars2, FaRegGrinTears, FaRegGrinTongueSquint, FaRegGrinTongueWink, FaRegGrinWink as FaRegGrinWink2, FaRegHandLizard, FaRegHandPaper, FaRegHandPeace, FaRegHandPointDown, FaRegHandPointLeft, FaRegHandPointRight, FaRegHandPointUp, FaRegHandPointer, FaRegHandRock, FaRegHandScissors, FaRegHandSpock, FaRegHandshake, FaRegHdd, FaRegHospital, FaRegHourglass, FaRegIdBadge, FaRegIdCard, FaRegKiss, FaRegKissBeam, FaRegKissWinkHeart, FaRegLaugh as FaRegLaugh2, FaRegLaughBeam as FaRegLaughBeam2, FaRegLaughSquint as FaRegLaughSquint2, FaRegLaughWink as FaRegLaughWink2, FaRegLightbulb as FaRegLightbulb2, FaRegListAlt as FaRegListAlt2, FaRegMap as FaRegMap2, FaRegMeh as FaRegMeh2, FaRegMehBlank as FaRegMehBlank2, FaRegMehRollingEyes as FaRegMehRollingEyes2, FaRegMinusSquare, FaRegMoneyBillAlt, FaRegMoon as FaRegMoon2, FaRegNewspaper as FaRegNewspaper2, FaRegObjectGroup, FaRegObjectUngroup, FaRegPaperPlane as FaRegPaperPlane2, FaRegPauseCircle, FaRegPlayCircle, FaRegPlusSquare, FaRegQuestionCircle as FaRegQuestionCircle2, FaRegRegistered, FaRegSadCry as FaRegSadCry2, FaRegSadTear as FaRegSadTear2, FaRegSave as FaRegSave2, FaRegShareSquare as FaRegShareSquare2, FaRegSmile as FaRegSmile2, FaRegSmileBeam as FaRegSmileBeam2, FaRegSmileWink as FaRegSmileWink2, FaRegSnowflake as FaRegSnowflake2, FaRegSquare, FaRegStar as FaRegStar2, FaRegStarHalf, FaRegStickyNote as FaRegStickyNote2, FaRegSun as FaRegSun2, FaRegSurprise as FaRegSurprise2, FaRegThumbsDown as FaRegThumbsDown3, FaRegThumbsUp as FaRegThumbsUp3, FaRegTimesCircle as FaRegTimesCircle2, FaRegTired as FaRegTired2, FaRegTrashAlt as FaRegTrashAlt2, FaRegUser as FaRegUser2, FaRegUserCircle as FaRegUserCircle2, FaRegUserSlash as FaRegUserSlash2, FaRegWindowClose as FaRegWindowClose2, FaRegWindowMaximize as FaRegWindowMaximize2, FaRegWindowMinimize as FaRegWindowMinimize2, FaRegWindowRestore as FaRegWindowRestore2 } from 'react-icons/fa';

const amenityIconMap = {
  bed: FaBed,
  'bed-sheets': FaBed,
  bath: FaBath,
  area: FaRulerCombined,
  'coffee-machine': FaCoffee,
  sugar: FaMugHot,
  'cutting-board': FaCut,
  microwave: FaBlender,
  cookware: FaUtensils,
  condiments: FaPepperHot,
  'coffee-tea': FaMugHot,
  refrigerator: FaSnowflake,
  tableware: FaWineGlass,
  utensils: FaUtensils,
  oven: FaBlender,
  kettle: FaMugHot,
  mug: FaMugHot,
  linens: FaTshirt,
  lock: FaLock,
  ac: FaFan,
  curtains: FaWindowMaximize,
  diffuser: FaSpa,
  iron: FaTshirt,
  games: FaGamepad,
  power: FaPlug,
  express: FaRegSmile,
  beach: FaUmbrellaBeach,
  pool: FaSwimmer,
  parking: FaCar,
  tv: FaTv,
  wifi: FaWifi,
  'hair-dryer': FaRegGrinStars,
  shampoo: FaSoap,
  bodywash: FaSoap,
  towel: FaTshirt,
  mattress: FaBed,
  pillow: FaRegGrinBeam,
  blanket: FaRegGrinHearts,
};

export default amenityIconMap;
